### ISSUE TITLE
涂抹之后,怎么得到涂抹之后的图呢??原谅我菜鸟...

### ISSUE THREAD

**Issue by xiaoyao20084321** [huangcheng1/ImageEdit#1]
涂抹之后,怎么得到涂抹之后的图呢??原谅我菜鸟...,3Q..

**Comment by huangcheng1** [comment]
最简单就是直接拿这个view的上下文构成image  。 image=UIGraphicsGetImageFromCurrentImageContext()

**Comment by huangcheng1** [comment]
@xiaoyao20084321 重新传了一个完整的。

**Comment by xiaoyao20084321** [comment]
好的,谢谢,,,
